[workspace]
resolver = "3"
members = [
    "core",
    "interface-native",
    "wasm-interface"
]

[workspace.dependencies]
hecs = "0.10.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
