[package]
name = "nation-of-last-land-core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hecs = "0.10.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
int = "0.3.0"
wasm-bindgen = "0.2"
